services:
  - type: web
    name: vetai-analyzer
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ..
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 5000 