services:
  - type: web
    name: vetai-analyzer
    env: node
    buildCommand: npm install && npm run install-client && npm run build-client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false 